version: '3.7'

services:
  app:
    build: .
    container_name: app
    environment:
      APP_DEBUG: ${APP_DEBUG}
      APP_PORT: ${APP_PORT}
      APP_ENABLE_SWAGGER: ${APP_ENABLE_SWAGGER}
    ports:
      - ${APP_PORT}:3006
    volumes:
      - ./src

  pg_db:
    container_name: pg_db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    ports:
      - $PG_PORT:5432
    networks:
      - bureau_backend

volumes:
  pg_db:
    name: pg_db

networks:
  bureau_backend:
    name: bureau_backend
