version: 1
disable_existing_loggers: false

formatters:
  default:
    use_colors: true
    format: "%(asctime)s.%(msecs)03d %(levelname)s %(module)s:%(lineno)d %(message)s"
    datefmt: "%Y%m%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn:
    error:
      propagate: true

root:
  level: INFO
  handlers: [console]
  propagate: false
