version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s.%(msecs)03d %(levelname)s %(module)s:%(lineno)d %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn:
    error:
      propagate: true

root:
  level: DEBUG
  handlers: [console]
  propagate: false
